import { Abi } from 'viem';

// Minimal ABI surface used by the frontend (reads + common actions)
export const EXCHANGE_ABI = [
    {
        type: 'function',
        name: 'deposit',
        stateMutability: 'payable',
        inputs: [],
        outputs: [],
    },
    {
        type: 'function',
        name: 'withdraw',
        stateMutability: 'nonpayable',
        inputs: [{ name: 'amount', type: 'uint256' }],
        outputs: [],
    },
    {
        type: 'function',
        name: 'placeOrder',
        stateMutability: 'nonpayable',
        inputs: [
            { name: 'isBuy', type: 'bool' },
            { name: 'price', type: 'uint256' },
            { name: 'amount', type: 'uint256' },
            { name: 'hintId', type: 'uint256' },
        ],
        outputs: [{ type: 'uint256' }],
    },
    {
        type: 'function',
        name: 'cancelOrder',
        stateMutability: 'nonpayable',
        inputs: [{ name: 'orderId', type: 'uint256' }],
        outputs: [],
    },
    {
        type: 'function',
        name: 'margin',
        stateMutability: 'view',
        inputs: [{ name: 'trader', type: 'address' }],
        outputs: [{ type: 'uint256' }],
    },
    {
        type: 'function',
        name: 'lockedMargin',
        stateMutability: 'view',
        inputs: [{ name: 'trader', type: 'address' }],
        outputs: [{ type: 'uint256' }],
    },
    {
        type: 'function',
        name: 'getPosition',
        stateMutability: 'view',
        inputs: [{ name: 'trader', type: 'address' }],
        outputs: [
            {
                type: 'tuple',
                components: [
                    { name: 'size', type: 'int256' },
                    { name: 'entryPrice', type: 'uint256' },
                    { name: 'realizedPnl', type: 'int256' },
                ],
            },
        ],
    },
    {
        type: 'function',
        name: 'orders',
        stateMutability: 'view',
        inputs: [{ name: 'id', type: 'uint256' }],
        outputs: [
            { name: 'id', type: 'uint256' },
            { name: 'trader', type: 'address' },
            { name: 'isBuy', type: 'bool' },
            { name: 'price', type: 'uint256' },
            { name: 'amount', type: 'uint256' },
            { name: 'initialAmount', type: 'uint256' },
            { name: 'timestamp', type: 'uint256' },
            { name: 'next', type: 'uint256' },
        ],
    },
    {
        type: 'function',
        name: 'bestBuyId',
        stateMutability: 'view',
        inputs: [],
        outputs: [{ type: 'uint256' }],
    },
    {
        type: 'function',
        name: 'bestSellId',
        stateMutability: 'view',
        inputs: [],
        outputs: [{ type: 'uint256' }],
    },
    {
        type: 'function',
        name: 'markPrice',
        stateMutability: 'view',
        inputs: [],
        outputs: [{ type: 'uint256' }],
    },
    {
        type: 'function',
        name: 'indexPrice',
        stateMutability: 'view',
        inputs: [],
        outputs: [{ type: 'uint256' }],
    },
    {
        type: 'function',
        name: 'cumulativeFundingRate',
        stateMutability: 'view',
        inputs: [],
        outputs: [{ type: 'int256' }],
    },
    {
        type: 'function',
        name: 'fundingInterval',
        stateMutability: 'view',
        inputs: [],
        outputs: [{ type: 'uint256' }],
    },
    {
        type: 'function',
        name: 'lastFundingTime',
        stateMutability: 'view',
        inputs: [],
        outputs: [{ type: 'uint256' }],
    },
    {
        type: 'function',
        name: 'insuranceFund',
        stateMutability: 'view',
        inputs: [],
        outputs: [{ type: 'uint256' }],
    },
    {
        type: 'function',
        name: 'initialMarginBps',
        stateMutability: 'view',
        inputs: [],
        outputs: [{ type: 'uint256' }],
    },
    {
        type: 'function',
        name: 'updateMarkPriceFromPyth',
        stateMutability: 'nonpayable',
        inputs: [],
        outputs: [],
    },
    {
        type: 'function',
        name: 'updateIndexPrice',
        stateMutability: 'nonpayable',
        inputs: [{ name: 'price', type: 'uint256' }],
        outputs: [],
    },
    {
        type: 'function',
        name: 'liquidate',
        stateMutability: 'nonpayable',
        inputs: [{ name: 'trader', type: 'address' }],
        outputs: [],
    },
    {
        type: 'event',
        name: 'TradeExecuted',
        inputs: [
            { name: 'buyOrderId', type: 'uint256', indexed: true },
            { name: 'sellOrderId', type: 'uint256', indexed: true },
            { name: 'price', type: 'uint256', indexed: false },
            { name: 'amount', type: 'uint256', indexed: false },
            { name: 'buyer', type: 'address', indexed: false },
            { name: 'seller', type: 'address', indexed: false },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'OrderPlaced',
        inputs: [
            { name: 'id', type: 'uint256', indexed: true },
            { name: 'trader', type: 'address', indexed: true },
            { name: 'isBuy', type: 'bool', indexed: false },
            { name: 'price', type: 'uint256', indexed: false },
            { name: 'amount', type: 'uint256', indexed: false },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'OrderRemoved',
        inputs: [{ name: 'id', type: 'uint256', indexed: true }],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'MarginDeposited',
        inputs: [
            { name: 'trader', type: 'address', indexed: true },
            { name: 'amount', type: 'uint256', indexed: false },
        ],
        anonymous: false,
    },
    {
        type: 'event',
        name: 'MarginWithdrawn',
        inputs: [
            { name: 'trader', type: 'address', indexed: true },
            { name: 'amount', type: 'uint256', indexed: false },
        ],
        anonymous: false,
    },
] as const satisfies Abi;

export type ExchangeAbi = typeof EXCHANGE_ABI;
